### PR TITLE
Skip WebSocket message parsing errors

### LINKED ISSUE #167: Critical Deserialization issue
Hi, i have been using this crate for months without issues and suddenly i get these errors: 
```
2023-08-12T23:41:01.307650Z ERROR chromiumoxide::conn: Failed to deserialize WS response data did not match any variant of untagged enum Message
2023-08-12T23:41:01.307668Z ERROR chromiumoxide::handler: WS Connection error: Serde(Error("data did not match any variant of untagged enum Message", line: 0, column: 0))
```
this makes no sense, i reinstalled the fetched (using the fetcher) chromium, reinstalled the crate. The code hasn't changed from when it worked...

This is highly blocking as my service depends heavily on this crate.

The only explaination i can imagine is that the `Message` enum depends on remote data and there is no catchall to resolve potential changes.

### PR DESCRIPTION
**Pull request by MOZGIII**
Fixes #167.

### CODE REVIEW

**Comment by Sytten** [comment]
@mattsse I think we need to get this merged at some point, I saw it a couple of times too depending on the browser version.

**Comment by MOZGIII** [comment]
This may have to be reworked such that it has no dependencies on the other PRs to move it forward, as the dependency PR seems to be stuck.

**Comment by Sytten** [comment]
@MOZGIII Would you mind rebasing it

**Comment by MOZGIII** [comment]
Nah, I've had enough rebasing - feel free to take care of it if you want it

**Comment by mattsse** [comment]
uff, very sorry for not getting to this in time -.-

@Sytten I assume this is still an issue?

**Comment by mattsse** [comment]
I see #243 

getting this in now

**Comment by Sytten** [comment]
Yeah but I will push a PR tomorrow to merge a few of the PR

**Comment by Sytten** [comment]
We also need a variant of #206 but I wanted to rewrite it.

**Review by mattsse — APPROVED** [review]

**Pull request merged**
