### PR TITLE
Added code to prevent zombie process in drop

### PR DESCRIPTION
**Pull request by sandmail32**
Killing process and not waiting on process leaves zombie process in linux
https://stackoverflow.com/questions/3857575/zombie-processes

added additional code like try_wait(); if developer wants to use asynchronous version of wait.
and expose child object if developer want to write custom kill logic.

sorry for the duplicate pull request.. i messed up the earlier one

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
thanks!

**Comment by sandmail32** [comment]
@mattsse Thanks for merging.
Can we release a new version on crates.io or do we have any roadmap?

**Comment by mattsse** [comment]
will do this week

**Comment by sandmail32** [comment]
Great!

**Pull request merged**
