### PR TITLE
Add stealth mode

### PR DESCRIPTION
**Pull request by escritorio-gustavo**
Create a `enable_stealth_mode` function on the `Page` struct based on
`headless_chrome`'s implementation to make it harder for websites to
block users of this crate

### CODE REVIEW

**Comment by escritorio-gustavo** [comment]
I implemented this on a `Page` level. It's probably possible to implement it on the `Browser` level and add it to the config builder, but I lack the knowledge of how to do it without breaking everything.

**Review by mattsse — COMMENTED** [review]
unfamiliar with all of this

> based on headless_chrome's implementation

could you please reference this

**Comment by escritorio-gustavo** [comment]
> could you please reference this

Sure, here is the PR where they implemented it
https://github.com/rust-headless-chrome/rust-headless-chrome/pull/360

**Review by mattsse — APPROVED** [review]
even though I'm not familiar with any of this, this seems reasonable and is only add on

**Pull request merged**
