### PR TITLE
Move cdp build step into an integration test

### PR DESCRIPTION
**Pull request by djc**
I noticed that chromiumoxide is one of the slowest crates to compile in our dependency graph. This is mainly due to the amount of generated code, but the process by which the generated code is included can also be changed to limit impact on downstream compile times; this is a first step towards improving the situation.

Replace the build script with an integration test that fails if the
generated code is out of date. This has several advantages:

* No need for downstream users to compile the build script
* No need for downstream users to compile the pdl crate
* No need for downstream users to run the code generation step
* The generated code is more usable in an IDE
* CI will fail if the generated code is out of date

The main downside is probably that the generated code is kept in
the repository, but this seems of relatively minimal impact,
especially if the code generator/source files don't change often.

### CODE REVIEW

**Comment by djc** [comment]
CI is suffering from the yanked futures crate here, maybe review/merge #79 first?

**Comment by mattsse** [comment]
good call, this is certainly reasonable given that it takes quite a bit of time..

> The main downside is probably that the generated code is kept in
the repository, but this seems of relatively minimal impact,
especially if the code generator/source files don't change often.

I agree that this is negligible and am in favor of merging this.

something's off in the CI with the futures dependency, maybe that version got yanked?

**Comment by djc** [comment]
Thanks for the review! If you could publish a fresh release, that would be great.

**Comment by mattsse** [comment]
just published 0.3.4 release
way faster :), thanks!

**Comment by djc** [comment]
Awesome, thanks!

**Pull request merged**
