### PR TITLE
Roll to chromium rev 1359167

### PR DESCRIPTION
**Pull request by Havunen**

### CODE REVIEW

**Review by mattsse — APPROVED** [review]

**Comment by Sytten** [comment]
Hey @Havunen can I ask you to also update the fetcher when you do an update to the CDP 🙏 
I will update it now to make sure it is still compatible, but ideally we keep them in sync.

**Comment by Sytten** [comment]
Update from my side, it seems that since chrome-for-testing has been released the chromium builds are all over the place and it is impossible to find a build that is available across all platforms.
Also this CDP is still not released, it is beta and IMO we should revert it since it will cause issues for most users.

**Comment by Havunen** [comment]
Hmm, maybe we should separate the CDP crate from this repository so it could follow different naming convention? Something to match the revision

**Comment by Sytten** [comment]
That actually a good idea, the CDP could follow the repo directly and be updated each time the CDP is changed. Then chromiumoxide oxide would pin the dependency. Puppeteer does that and tag the version to 0.0.<revision>

 What do you think @mattsse

**Pull request merged**
