### PR TITLE
Log raw WS messages to facilitate the debugging

### PR DESCRIPTION
**Pull request by MOZGIII**

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
I'm okay with logging these without a new feature

**Comment by MOZGIII** [comment]
I'd like to be able to turn these off though, as it's an extra copy on every message; would you consider keeping a feature but making it on by default? That way I can turn it off when needed.

I'm kind of interested in tuning performance here, as we could have a quite overhead-sensitive setup (proper measurements to confirm this are pending).

**Comment by ryo33** [comment]
> I'd like to be able to turn these off though, as it's an extra copy on every message; would you consider keeping a feature but making it on by default? That way I can turn it off when needed.

Extra cloning can be avoided by this statement.

```rust
let msg_for_debug = if tracing::enabled!(target: "chromiumoxide::conn::raw_ws::parse_errors", tracing::Level::DEBUG) {
    Some(msg.clone)
} else {
    None
};
```

**Comment by ryo33** [comment]
I forked this branch and opened https://github.com/mattsse/chromiumoxide/pull/204.
It's zero-copy.

**Pull request closed without merging**
